name: ssm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pandas=1.5.3
  - scipy
  - scikit-learn
  - seaborn
  - matplotlib
  - kneed
  - boto3
  - h5py
  - pynwb
  - pip
  - pip:
      - ssm




